/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Livestream } from "./Livestream";
import { LivestreamCountArgs } from "./LivestreamCountArgs";
import { LivestreamFindManyArgs } from "./LivestreamFindManyArgs";
import { LivestreamFindUniqueArgs } from "./LivestreamFindUniqueArgs";
import { CreateLivestreamArgs } from "./CreateLivestreamArgs";
import { UpdateLivestreamArgs } from "./UpdateLivestreamArgs";
import { DeleteLivestreamArgs } from "./DeleteLivestreamArgs";
import { Event } from "../../event/base/Event";
import { LivestreamService } from "../livestream.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Livestream)
export class LivestreamResolverBase {
  constructor(
    protected readonly service: LivestreamService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "read",
    possession: "any",
  })
  async _livestreamsMeta(
    @graphql.Args() args: LivestreamCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Livestream])
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "read",
    possession: "any",
  })
  async livestreams(
    @graphql.Args() args: LivestreamFindManyArgs
  ): Promise<Livestream[]> {
    return this.service.livestreams(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Livestream, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "read",
    possession: "own",
  })
  async livestream(
    @graphql.Args() args: LivestreamFindUniqueArgs
  ): Promise<Livestream | null> {
    const result = await this.service.livestream(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Livestream)
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "create",
    possession: "any",
  })
  async createLivestream(
    @graphql.Args() args: CreateLivestreamArgs
  ): Promise<Livestream> {
    return await this.service.createLivestream({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Livestream)
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "update",
    possession: "any",
  })
  async updateLivestream(
    @graphql.Args() args: UpdateLivestreamArgs
  ): Promise<Livestream | null> {
    try {
      return await this.service.updateLivestream({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Livestream)
  @nestAccessControl.UseRoles({
    resource: "Livestream",
    action: "delete",
    possession: "any",
  })
  async deleteLivestream(
    @graphql.Args() args: DeleteLivestreamArgs
  ): Promise<Livestream | null> {
    try {
      return await this.service.deleteLivestream(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async getEvent(@graphql.Parent() parent: Livestream): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
